#!/bin/bash

echo "🚀 Setting up TechVerse Campus Portal TurboRepo..."

# Check if bun is installed
if ! command -v bun &> /dev/null; then
    echo "❌ Bun is not installed. Please install Bun first:"
    echo "curl -fsSL https://bun.sh/install | bash"
    exit 1
fi

echo "✅ Bun found"

# Clean any existing node_modules and lock files
echo "🧹 Cleaning up existing dependencies..."
rm -rf node_modules
rm -rf apps/web/node_modules
rm -f bun.lockb
rm -f apps/web/bun.lockb

# Install root dependencies
echo "📦 Installing root dependencies..."
bun install

# Install web app dependencies
echo "📦 Installing web app dependencies..."
cd apps/web
bun install
cd ../..

echo "🎨 Setting up TailwindCSS..."
cd apps/web
# Initialize Tailwind if needed
if [ ! -f "tailwind.config.ts" ]; then
    bun add -D tailwindcss autoprefixer postcss
fi
cd ../..

echo "🧱 Setting up ShadCN UI components..."
cd apps/web

# Install shadcn CLI if not installed
if ! command -v shadcn-ui &> /dev/null; then
    bun add -g shadcn-ui
fi

# Add additional shadcn components that might be missing
echo "Adding ShadCN UI components..."
bun add @radix-ui/react-switch @radix-ui/react-tabs @radix-ui/react-progress

cd ../..

echo "🔧 Creating additional config files..."

# Create .env.local for web app
cat > apps/web/.env.local << EOF
NEXT_PUBLIC_APP_NAME="TechVerse Student Portal"
NEXT_PUBLIC_APP_VERSION="1.0.0"
EOF

# Create prettier config
cat > .prettierrc << EOF
{
  "semi": true,
  "trailingComma": "es5",
  "singleQuote": false,
  "tabWidth": 2,
  "useTabs": false
}
EOF

# Create .gitignore if it doesn't exist
if [ ! -f ".gitignore" ]; then
cat > .gitignore << EOF
# Dependencies
node_modules/
/.pnp
.pnp.js
bun.lockb

# Production
build/
dist/
out/

# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*
bun-debug.log*
bun-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage/
*.lcov

# nyc test coverage
.nyc_output

# Dependency directories
node_modules/

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next

# Nuxt.js build / generate output
.nuxt
dist

# Storybook build outputs
.out
.storybook-out

# Temporary folders
tmp/
temp/

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# OS generated files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# TurboRepo
.turbo
EOF
fi

echo "🏗️  Building the project..."
bun run build

echo "🎉 Setup complete! 

To start the development server:
  bun dev

To build the project:
  bun build

To lint the project:
  bun lint

The application will be available at http://localhost:3000

🎓 TechVerse Student Portal is ready to go!"